# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1

      # Runs a single command using the runners shell
      - name: run gulp
        run: npm run gulp

      - uses: actions/upload-artifact@v2
        with:
          name: Feed-and-Projects
          path:  |
            feed.xml
            projects.html
      - id: initial
        uses: juztcode/gitter-github-action@v1
        with:
          room-id: ${{ secrets.GITTER_ROOM_ID }}
          token: ${{ secrets.GITTER_TOKEN }}
          text: Pending

      - uses: juztcode/gitter-github-action@v1
        with:
          room-id: ${{ secrets.GITTER_ROOM_ID }}
          token: ${{ secrets.GITTER_TOKEN }}
          text: Success
          message-id: ${{ steps.initial.outputs.message-id }}


  release:
    name: 'Release'
    needs: build
    if: github.event_name == 'push' && github.repository == 'hackergarten/hackergarten.github.io' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: Feed-and-Projects
          path:  |
            feed.xml
            projects.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: master
